---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql5
  namespace: ase-ns-00
spec:
  selector:
    matchLabels:
      app: mysql5
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql5
    spec:
      containers:
        - name: mysql5
          image: registry.cn-shanghai.aliyuncs.com/xywu/mysql5:demo
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
          ports:
            - containerPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-server
  namespace: ase-ns-00
spec:
  selector:
    matchLabels:
      app: student-server
  template:
    metadata:
      labels:
        app: student-server
    spec:
      containers:
        - name: student-server
          image: registry.cn-shanghai.aliyuncs.com/xywu/student-server:demo
          imagePullPolicy: Always
          env:
            - name: USERNAME
              value: "root"
            - name: PASSWORD
              value: "password"
            - name: DB_URL
              value: "mysql5:3306/student"
          ports:
            - containerPort: 9999

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ase-ns-00
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: registry.cn-shanghai.aliyuncs.com/xywu/frontend:demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysql5
  namespace: ase-ns-00
spec:
  ports:
    - port: 3306
  selector:
    app: mysql5

---
apiVersion: v1
kind: Service
metadata:
  name: student-server
  namespace: ase-ns-00
spec:
  ports:
    - port: 9999
  selector:
    app: student-server

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ase-ns-00
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 1024
      targetPort: 80
