version: "3"
services:
  mysql5:
    build: mysql_employee/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3307
    networks:
      - mynetwork

  employee-server:
    depends_on:
      - mysql5
    build: employee-server/
    restart: always
    environment:
      USERNAME: root
      PASSWORD: password
      DB_URL: mysql5:3306/employee
    ports:
      - 9999:9999
    networks:
      - mynetwork

networks:
  mynetwork: {}
