version: "3"
services:
  mysql5-employee:
    build: mysql_employee/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    networks:
      - mynetwork
    volumes:
      - employee-data:/var/lib/mysql

  employee-server:
    depends_on:
      - mysql5-employee
    build: employee-server/
    restart: always
    environment:
      USERNAME: root
      PASSWORD: password
      DB_URL: mysql5-employee:3306/employee
    ports:
      - 9999:9999
    networks:
      - mynetwork

  mysql5-user:
    build: mysql_user/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3306
    networks:
      - mynetwork
    volumes:
      - user-data:/var/lib/mysql

  user-server:
    depends_on:
      - mysql5-user
    build: user-server/
    restart: always
    environment:
      USERNAME: root
      PASSWORD: password
      DB_URL: mysql5-user:3306/user
    ports:
      - 9998:9998
    networks:
      - mynetwork

  mysql5-task:
    build: mysql_task/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3309:3306
    networks:
      - mynetwork
    volumes:
      - task-data:/var/lib/mysql

  task-server:
    depends_on:
      - mysql5-task
    build: task-server/
    restart: always
    environment:
      USERNAME: root
      PASSWORD: password
      DB_URL: mysql5-task:3306/task
    ports:
      - 9997:9997
    networks:
      - mynetwork

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - 2181:2181
    networks:
      - mynetwork

  kafka:
    image: wurstmeister/kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"
    links:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    networks:
      - mynetwork

  taskcompletion-server:
    depends_on:
      - employee-server
      - task-server
    build: taskCompletion-server/
    restart: always
    ports:
      - 9996:9996
    networks:
      - mynetwork

networks:
  mynetwork: {}

volumes:
  employee-data: {}
  user-data: {}
  task-data: {}
