version: "3"
services:
  mysql5-employee:
    build: mysql_employee/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3307
    networks:
      - mynetwork

  employee-server:
    depends_on:
      - mysql5-employee
    build: employee-server/
    restart: always
    environment:
      USERNAME: root
      PASSWORD: password
      DB_URL: mysql5-employee:3306/employee
    ports:
      - 9999:9999
    networks:
      - mynetwork

  mysql5-user:
    build: mysql_user/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3308
    networks:
      - mynetwork

  user-server:
    depends_on:
      - mysql5-user
    build: user-server/
    restart: always
    environment:
      USERNAME: root
      PASSWORD: password
      DB_URL: mysql5-user:3306/user
    ports:
      - 9998:9998
    networks:
      - mynetwork

  mysql5-task:
    build: mysql_task/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3309:3309
    networks:
      - mynetwork

  task-server:
    depends_on:
      - mysql5-task
    build: task-server/
    restart: always
    environment:
      USERNAME: root
      PASSWORD: password
      DB_URL: mysql5-task:3306/task
    ports:
      - 9997:9997
    networks:
      - mynetwork

networks:
  mynetwork: {}
