server:
  port: 9997
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_URL}?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  kafka:
    bootstrap-servers: pj_kafka_1:9092
    consumer:
      bootstrap-servers: pj_kafka_1:9092
      group-id: 2
